---
# geerlingguy.firewall roles
firewall_allowed_tcp_ports:
  - "22"
  - "9100"
  - "8080"

# loki-docker-plugin variables
skip_loki_url_verification: true
loki_url: "{{ hostvars['central_node']['loki_url'] }}"

# exporter-node role variables
reverse_proxy_setup: false
exporters_endpoints:
  nodeexporter: 9100
  cadvisor: 8080
