---
- hosts: central_node
  become: true

  pre_tasks:
    - name: Update packages cache.
      import_tasks: "common/pre_tasks.yml"

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.docker

  tasks:
    - name: Install loki plugin if monitoring on node enabled.
      include_role:
        name: loki-docker-plugin
      when: gather_logs_on_node

    - name: Provision monitoring services.
      import_role:
        name: central-node
