version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/Caddyfile:/Caddyfile
      - caddy_data:/data
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
      - CADDY_INGRESS_NETWORKS=caddy
    restart: unless-stopped

  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: localhost
      caddy.handle_path: /whoami
      caddy.handle_path.0_reverse_proxy: "{{upstreams 8000}}"

  httpd:
    image: httpd
    networks:
      - caddy
    labels:
      caddy: localhost
      caddy.handle_path: /httpd
      caddy.handle_path.0_reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    name: caddy

volumes:
  caddy_data:
