---
- hosts: all

  pre_tasks:
    - name: Import common pre tasks.
      import_tasks: "common/pre_tasks.yml"

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.docker

- hosts: central_node

  pre_tasks:
    - name: Import common pre tasks.
      import_tasks: "common/pre_tasks.yml"

- hosts: worker_nodes

  pre_tasks:
    - name: Import common pre tasks.
      import_tasks: "common/pre_tasks.yml"
