---
route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "Prometheus"
        channel: "#infra-alerts"
        api_url: "https://hooks.slack.com/services/<webhook-id>"
