---
# tasks file for loki-docker-plugin
- name: "Verify that loki_url is set."
  assert:
    that:
      - loki_url is defined
    fail_msg: "{{ loki_url }} needs to be set for the role to work"
    success_msg: "Required variable {{ loki_url }} is defined"

- name: "Check if loki is ready."
  uri:
    url: "{{ loki_url }}/ready"
    return_content: yes
  register: response
  until: response.status == 200 and 'ready' in response.content
  retries: 10
  delay: 10

- name: Create docker daemon config.
  copy:
    content: "{{ daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker

- name: Install loki docker plugin.
  community.docker.docker_plugin:
    plugin_name: "grafana/loki-docker-driver:latest"
    state: "present"
    alias: "loki"
  notify: restart docker

- name: Enable loki docker plugin.
  community.docker.docker_plugin:
    plugin_name: "loki"
    state: "enable"
  notify: restart docker
