---
# tasks file for central-node
- name: Ensure {{ target_directory }} directory exists.
  file:
    path: "{{ target_directory }}"
    state: directory
    mode: 0664

- name: Sync monitoring services configs.
  synchronize:
    src: docker
    dest: "{{ target_directory }}"
    rsync_opts:
      - "--exclude=docker-compose.yml"

- name: Copy alertmanager template.
  template:
    src: alertmanager.yml.j2
    dest: ansible_env.HOME/monitoring-stack/alertmanager/alertmanager.yml
    mode: 0644

- name: Copy reverse proxy docker-compose template.
  template:
    src: docker-compose-dns.yml.j2
    dest: ansible_env.HOME/monitoring-stack/docker-compose.yml
    mode: 0644
  when: reverse_proxy_setup

- name: Copy ip (ports) docker-compose template.
  template:
    src: docker-compose-ip.yml.j2
    dest: ansible_env.HOME/monitoring-stack/docker-compose.yml
    mode: 0644
  when: not reverse_proxy_setup

- name: Start monitoring services.
  community.docker.docker_compose:
    project_src: "{{ target_directory }}"
    pull: yes
