---
- name: Converge
  hosts: all
  vars:
    - pip_install_packages:
        - name: docker
        - name: six
        - name: docker-compose
  vars_files:
    - converge-vars.yml

  pre_tasks:
    - name: Update packages cache.
      import_tasks: "../../../../common/pre_tasks.yml"

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: "Include exporter-node"
      include_role:
        name: "exporter-node"
