---
galaxy_info:
  author: Leszk Blazewski
  description: Install monitoring stack based on prometheus, grafana, loki running in docker
  company: ""
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - monitoring
    - docker
    - prometheus
    - grafana
    - loki

dependencies: []
